<?php

declare(strict_types=1);

/*
 *  This file is part of the Micro framework package.
 *
 *  (c) Stanislau Komar <kost@micro-php.net>
 *
 *  For the full copyright and license information, please view the LICENSE
 *  file that was distributed with this source code.
 */

namespace Micro\Component\DependencyInjection\Proxy;

/** @psalm-suppress UnusedClass */
final class ProxyBuilder implements ProxyBuilderInterface
{
    /**
     * @var class-string[]
     */
    private array $classCollection;

    public function __construct(
        private readonly ProxyClassContentFactoryInterface $classContentFactory,
        private readonly ProxyFileManagerInterface $proxyFileManager,
        private readonly string $proxyClassesNamespace = 'Micro\ClassProxy',
    ) {
        $this->classCollection = [];
    }

    #[\Override]
    public function add(string $className): ProxyBuilderInterface
    {
        if (\in_array($className, $this->classCollection)) {
            return $this;
        }

        $this->classCollection[] = $className;

        return $this;
    }

    #[\Override]
    public function build(): void
    {
        $namespace = $this->proxyClassesNamespace ? 'namespace '.$this->proxyClassesNamespace : '';
        $proxyClassContent = "
<?php

declare(strict_types=1);

{$namespace};

use Psr\Container\ContainerInterface;

/*
 * This file is auto-generated by the MicroPHP library `micro/dependency-injection`.
 * 
 * Any manual modifications to this file will be overwritten the next time the proxy classes are generated.
 * 
 * Generated classes are intended to facilitate dependency injection by creating proxy implementations.
 * Users are advised to configure and use the dependency injection framework as documented.
 * 
 * The authors and contributors of this library are not liable for any direct, indirect, incidental, special, exemplary, or consequential damages
 * (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption)
 * however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this software, even if advised of the possibility of such damage.
 * 
 * For more information, refer to the official documentation at: https://micro-php.net/
 */
 
";
        foreach ($this->classCollection as $className) {
            $proxyClassContent .= "\n".$this->classContentFactory->create($className);
        }

        $this->proxyFileManager->writeProxiesFileContent($proxyClassContent);
        $this->proxyFileManager->requireProxiesFile();
    }
}
