name: Plugin CI
on:
  push:
    branches: [ 'master' ]
  pull_request:

jobs:
  tests:
    name: "Tests ${{ matrix.php-version }} deps ${{ matrix.dependency-versions }}"
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        # normal, highest, non-dev installs
        php-version: [ '8.1', '8.2' ]
        dependency-versions: [ 'highest' ]
        include:
          # testing lowest PHP version with the lowest dependencies
          - php-version: '8.1'
            dependency-versions: 'lowest'

          # testing dev versions with the highest PHP
          - php-version: '8.2'
            dependency-versions: 'highest'

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Composer install"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependency-versions }}"
          composer-options: "--prefer-dist --no-progress"

      - name: "Run tests"
        run: "./vendor/bin/phpunit"
