on: [pull_request]
name: Static analysis

jobs:
  composer-validate:
    name: Composer validate & normalize
    runs-on: ubuntu-22.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer-normalize

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate
        run: composer validate --strict

      - name: Normalize
        run: composer-normalize --dry-run

  phpcs:
    name: PHP_CodeSniffer
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: squizlabs/php_codesniffer:^3.7

      - name: Download dependencies
        uses: ramsey/composer-install@v2

      - name: Testing
        run: composer statics